"""Limit per user

Revision ID: 36a92d9eb5c1
Revises: a91fa3f8e875
Create Date: 2020-04-03 08:03:00.086238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a92d9eb5c1'
down_revision = 'a91fa3f8e875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('limit_per_user', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('max_per_user', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('added_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'added_id')
    op.drop_column('rooms', 'max_per_user')
    op.drop_column('rooms', 'limit_per_user')
    # ### end Alembic commands ###
