"""Initial

Revision ID: a91fa3f8e875
Revises: 
Create Date: 2020-03-27 15:17:15.065140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91fa3f8e875'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('room_type', sa.Enum('simple', 'random', 'fav', name='roomtype'), nullable=True),
    sa.Column('allow_downvote', sa.Boolean(), nullable=True),
    sa.Column('downvote_threeshold', sa.Integer(), nullable=True),
    sa.Column('admin', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_key'), 'rooms', ['key'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_index(op.f('ix_rooms_key'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
